// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.GitKraken
{
    internal sealed partial class Vsix
    {
        public const string Id = "VS-GitKraken";
        public const string Name = "GitKraken";
        public const string Description = @"Adds a context menu item to the solution explorer (specifically the Solution Node context menu), to open the underlying Git repository in GitKraken - with more to come!";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Coding With Calvin";
        public const string Tags = "gitkraken, git, keif";
    }
}
