// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.GitKraken
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "a0117989-26fe-4409-af6b-db16115dcf3a";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidOpenInGKCmdSetString = "f6086186-9021-452d-9d3b-b46ca285a57d";
        public static Guid guidOpenInGKCmdSet = new Guid(guidOpenInGKCmdSetString);

        public const string guidIconsString = "a6058340-772e-4dd9-a796-1c36106495bd";
        public static Guid guidIcons = new Guid(guidIconsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OpenInGK = 0x0100;
        public const int GitKraken = 0x0001;
    }
}